apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
  namespace: hermes
  labels:
    system: openstack
    service: audit
    component: elasticsearch
spec:
  clusterIP: None
  selector:
    app: {{ template "hermes.name" . }}
    chart: {{ template "hermes.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: elasticsearch
  ports:
    - name: transport
      port: 9300
      protocol: TCP
